name: locale_loom_app
description: "Discover local gems, explore ratings, and find nearby places effortlessly with our app, ExploreHub"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2  # Url
  provider: ^6.1.1  # State management library
  http: ^1.1.2  # HTTP client for making network requests
  flutter_styled_toast: ^2.2.1  # Styled toast messages for Flutter
  geolocator: ^10.1.0  # Plugin for accessing device location
  geocoding: ^2.0.4  # Geocoding (converting addresses to coordinates and vice versa)
  flutter_cache_manager: ^3.3.1  # Cache manager for Flutter
  sqflite: ^2.3.0  # SQLite database plugin for Flutter
  path: ^1.8.3  # Provides common operations on file and directory paths
  async_builder: ^1.2.0  # Library for building async widgets with a simple syntax

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
